// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bibliotheque.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bibliothequeDe = `-- name: BibliothequeDe :many

SELECT id, category, name, competition, supports
FROM library_entries
WHERE structure = $1
ORDER BY category, name
`

type BibliothequeDeRow struct {
	ID          pgtype.UUID
	Category    LibraryCategory
	Name        string
	Competition bool
	Supports    []string
}

// La bibliothèque : `library_entries`, une par structure, unique par
// (structure, category, name).
func (q *Queries) BibliothequeDe(ctx context.Context, dans string) ([]BibliothequeDeRow, error) {
	rows, err := q.db.Query(ctx, bibliothequeDe, dans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BibliothequeDeRow
	for rows.Next() {
		var i BibliothequeDeRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Competition,
			&i.Supports,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const creerEntree = `-- name: CreerEntree :one
INSERT INTO library_entries (structure, category, name, competition, supports, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (structure, category, name) DO NOTHING
RETURNING id
`

type CreerEntreeParams struct {
	Dans        string
	Categorie   LibraryCategory
	Nom         string
	Competition bool
	Supports    []string
	CreatedBy   *string
}

// Insert atomique : conflit (structure, category, name) → aucune ligne.
func (q *Queries) CreerEntree(ctx context.Context, arg CreerEntreeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, creerEntree,
		arg.Dans,
		arg.Categorie,
		arg.Nom,
		arg.Competition,
		arg.Supports,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const definirSupports = `-- name: DefinirSupports :exec
UPDATE library_entries SET supports = $1 WHERE id = $2
`

type DefinirSupportsParams struct {
	Supports []string
	ID       pgtype.UUID
}

// ⚠️ Le VIDE n'existe pas en base (`library_entries_supports`) : l'appelant
// passe NULL pour « ne soutient rien ».
func (q *Queries) DefinirSupports(ctx context.Context, arg DefinirSupportsParams) error {
	_, err := q.db.Exec(ctx, definirSupports, arg.Supports, arg.ID)
	return err
}

const entreeParId = `-- name: EntreeParId :one
SELECT structure, category, name, competition, supports
FROM library_entries
WHERE id = $1
`

type EntreeParIdRow struct {
	Structure   string
	Category    LibraryCategory
	Name        string
	Competition bool
	Supports    []string
}

func (q *Queries) EntreeParId(ctx context.Context, id pgtype.UUID) (EntreeParIdRow, error) {
	row := q.db.QueryRow(ctx, entreeParId, id)
	var i EntreeParIdRow
	err := row.Scan(
		&i.Structure,
		&i.Category,
		&i.Name,
		&i.Competition,
		&i.Supports,
	)
	return i, err
}

const marquerCompetition = `-- name: MarquerCompetition :exec
UPDATE library_entries SET competition = $1 WHERE id = $2
`

type MarquerCompetitionParams struct {
	Competition bool
	ID          pgtype.UUID
}

func (q *Queries) MarquerCompetition(ctx context.Context, arg MarquerCompetitionParams) error {
	_, err := q.db.Exec(ctx, marquerCompetition, arg.Competition, arg.ID)
	return err
}

const nomDejaPris = `-- name: NomDejaPris :one
SELECT EXISTS(
  SELECT 1 FROM library_entries e
  WHERE structure = $1 AND category = $2 AND name = $3 AND id <> $4
)::boolean AS pris
`

type NomDejaPrisParams struct {
	Dans      string
	Categorie LibraryCategory
	Nom       string
	ID        pgtype.UUID
}

func (q *Queries) NomDejaPris(ctx context.Context, arg NomDejaPrisParams) (bool, error) {
	row := q.db.QueryRow(ctx, nomDejaPris,
		arg.Dans,
		arg.Categorie,
		arg.Nom,
		arg.ID,
	)
	var pris bool
	err := row.Scan(&pris)
	return pris, err
}

const renommerEntree = `-- name: RenommerEntree :exec
UPDATE library_entries SET name = $1 WHERE id = $2
`

type RenommerEntreeParams struct {
	Nom string
	ID  pgtype.UUID
}

func (q *Queries) RenommerEntree(ctx context.Context, arg RenommerEntreeParams) error {
	_, err := q.db.Exec(ctx, renommerEntree, arg.Nom, arg.ID)
	return err
}
