// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptResult string

const (
	AttemptResultRep   AttemptResult = "rep"
	AttemptResultNorep AttemptResult = "norep"
)

func (e *AttemptResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptResult(s)
	case string:
		*e = AttemptResult(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptResult: %T", src)
	}
	return nil
}

type NullAttemptResult struct {
	AttemptResult AttemptResult
	Valid         bool // Valid is true if AttemptResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptResult) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptResult), nil
}

type AttemptTier string

const (
	AttemptTierPessimistic AttemptTier = "pessimistic"
	AttemptTierRealistic   AttemptTier = "realistic"
	AttemptTierOptimistic  AttemptTier = "optimistic"
)

func (e *AttemptTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptTier(s)
	case string:
		*e = AttemptTier(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptTier: %T", src)
	}
	return nil
}

type NullAttemptTier struct {
	AttemptTier AttemptTier
	Valid       bool // Valid is true if AttemptTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptTier) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptTier), nil
}

type CoachAvailability string

const (
	CoachAvailabilityPending     CoachAvailability = "pending"
	CoachAvailabilityAvailable   CoachAvailability = "available"
	CoachAvailabilityUnavailable CoachAvailability = "unavailable"
)

func (e *CoachAvailability) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoachAvailability(s)
	case string:
		*e = CoachAvailability(s)
	default:
		return fmt.Errorf("unsupported scan type for CoachAvailability: %T", src)
	}
	return nil
}

type NullCoachAvailability struct {
	CoachAvailability CoachAvailability
	Valid             bool // Valid is true if CoachAvailability is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoachAvailability) Scan(value interface{}) error {
	if value == nil {
		ns.CoachAvailability, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoachAvailability.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoachAvailability) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoachAvailability), nil
}

type CyclePhase string

const (
	CyclePhaseMenstruation CyclePhase = "menstruation"
	CyclePhaseFollicular   CyclePhase = "follicular"
	CyclePhaseOvulation    CyclePhase = "ovulation"
	CyclePhaseLuteal       CyclePhase = "luteal"
)

func (e *CyclePhase) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CyclePhase(s)
	case string:
		*e = CyclePhase(s)
	default:
		return fmt.Errorf("unsupported scan type for CyclePhase: %T", src)
	}
	return nil
}

type NullCyclePhase struct {
	CyclePhase CyclePhase
	Valid      bool // Valid is true if CyclePhase is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCyclePhase) Scan(value interface{}) error {
	if value == nil {
		ns.CyclePhase, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CyclePhase.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCyclePhase) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CyclePhase), nil
}

type EventType string

const (
	EventTypeCompetition EventType = "competition"
	EventTypeVacation    EventType = "vacation"
	EventTypeTravel      EventType = "travel"
	EventTypeRest        EventType = "rest"
	EventTypeOther       EventType = "other"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType
	Valid     bool // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type Gender string

const (
	GenderM Gender = "M"
	GenderF Gender = "F"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender
	Valid  bool // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type LibraryCategory string

const (
	LibraryCategoryExercices   LibraryCategory = "exercices"
	LibraryCategoryVariantes   LibraryCategory = "variantes"
	LibraryCategoryAssistances LibraryCategory = "assistances"
	LibraryCategoryTempos      LibraryCategory = "tempos"
	LibraryCategoryFormats     LibraryCategory = "formats"
)

func (e *LibraryCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibraryCategory(s)
	case string:
		*e = LibraryCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for LibraryCategory: %T", src)
	}
	return nil
}

type NullLibraryCategory struct {
	LibraryCategory LibraryCategory
	Valid           bool // Valid is true if LibraryCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibraryCategory) Scan(value interface{}) error {
	if value == nil {
		ns.LibraryCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibraryCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibraryCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibraryCategory), nil
}

type AccesSupport struct {
	ID        pgtype.UUID
	Uid       string
	AthleteID pgtype.UUID
	Debut     pgtype.Timestamptz
	Fin       pgtype.Timestamptz
}

type Athlete struct {
	ID            pgtype.UUID
	LegacyID      *string
	FirstName     string
	LastName      string
	Email         *string
	HeightCm      pgtype.Numeric
	WeightKg      pgtype.Numeric
	BirthDate     pgtype.Date
	PoidsDepartKg pgtype.Numeric
	PoidsDepartLe pgtype.Date
	Gender        *Gender
	Structure     string
	CoachUid      string
	UserUid       *string
	KineUid       *string
	CurrentOneRm  []byte
	CreatedAt     pgtype.Timestamptz
	ArchiveLe     pgtype.Timestamptz
}

type AthleteGoal struct {
	ID         pgtype.UUID
	AthleteID  pgtype.UUID
	LegacyID   *string
	Exercise   *string
	Sets       string
	Reps       string
	Weight     string
	Motivation string
	CreatedOn  pgtype.Date
	AchievedOn pgtype.Date
	Categorie  LibraryCategory
	Structure  string
}

type AthletePr struct {
	ID          pgtype.UUID
	AthleteID   pgtype.UUID
	Movement    *string
	Reps        int32
	WeightKg    pgtype.Numeric
	Sets        *string
	Format      *string
	Variant     *string
	PerformedOn pgtype.Date
	Categorie   LibraryCategory
	Structure   string
}

type Bilan struct {
	ID          pgtype.UUID
	AthleteID   pgtype.UUID
	ModeleID    pgtype.UUID
	ModeleNom   string
	BilanDate   pgtype.Date
	KineUid     *string
	Statut      string
	Antecedents *string
	Notes       *string
	CreeLe      pgtype.Timestamptz
	ModifieLe   pgtype.Timestamptz
}

type BilanMediasDemo struct {
	ID      pgtype.UUID
	Chemin  string
	Type    string
	Legende *string
	CreePar *string
	CreeLe  pgtype.Timestamptz
}

type BilanModele struct {
	ID          pgtype.UUID
	Nom         string
	Description *string
	CreePar     *string
	Archive     bool
	CreeLe      pgtype.Timestamptz
	ModifieLe   pgtype.Timestamptz
}

type BilanResultat struct {
	ID              pgtype.UUID
	BilanID         pgtype.UUID
	TestID          pgtype.UUID
	TestLibelle     string
	RubriqueLibelle *string
	Protocole       *string
	Vues            []string
	Cible           *string
	Mesure          string
	Bilateral       bool
	Ordre           *int32
	Ressenti        *string
	Detail          *string
	MesureGauche    pgtype.Numeric
	MesureDroite    pgtype.Numeric
	ChargeKg        pgtype.Numeric
	Materiel        *string
	ModifieLe       pgtype.Timestamptz
}

type BilanResultatMedia struct {
	ResultatID pgtype.UUID
	MediaID    pgtype.UUID
	Ordre      int32
}

type BilanRubrique struct {
	ID       pgtype.UUID
	ModeleID pgtype.UUID
	Libelle  string
	Ordre    int32
}

type BilanTest struct {
	ID         pgtype.UUID
	RubriqueID pgtype.UUID
	Libelle    string
	Protocole  *string
	Mesure     string
	Bilateral  bool
	ChargeKg   pgtype.Numeric
	Materiel   *string
	Vues       []string
	Cible      *string
	Ordre      int32
	Retire     bool
}

type BilanTestMedia struct {
	TestID  pgtype.UUID
	MediaID pgtype.UUID
	Ordre   int32
}

type BlockObjective struct {
	ID         pgtype.UUID
	BlockID    pgtype.UUID
	Position   int32
	Exercise   *string
	Variant    *string
	Format     *string
	Sets       *string
	Reps       *string
	WeightMin  *string
	WeightMax  *string
	Assistance *string
	AtteintLe  pgtype.Date
	Categorie  LibraryCategory
	Structure  string
}

type CalendarEvent struct {
	ID        pgtype.UUID
	LegacyID  *string
	AthleteID pgtype.UUID
	Type      EventType
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Emoji     *string
	CanTrain  *bool
}

type Coach struct {
	Uid       string
	CreatedAt pgtype.Timestamptz
	Structure string
}

type CoachProfile struct {
	CoachUid  string
	Slug      string
	Accroche  *string
	Bio       *string
	Instagram *string
	PhotoUrl  *string
	OneRm     []byte
	Langues   []string
}

type Competition struct {
	ID          pgtype.UUID
	LegacyID    *string
	Name        string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Location    *string
	MaxAttempts int32
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
	Structure   string
}

type CompetitionAttempt struct {
	ID                pgtype.UUID
	ParticipantID     pgtype.UUID
	MovementID        pgtype.UUID
	AttemptIndex      int32
	WeightKg          pgtype.Numeric
	Result            *AttemptResult
	WeightPessimistic pgtype.Numeric
	WeightRealistic   pgtype.Numeric
	WeightOptimistic  pgtype.Numeric
	SelectedTier      *AttemptTier
	NorepReason       *string
	VarUsed           *bool
}

type CompetitionCoachAvailability struct {
	CompetitionID pgtype.UUID
	CoachUid      string
	Day           pgtype.Date
	Status        CoachAvailability
	UpdatedAt     pgtype.Timestamptz
}

type CompetitionEditor struct {
	CompetitionID pgtype.UUID
	EditorUid     string
}

type CompetitionFlight struct {
	ID            pgtype.UUID
	CompetitionID pgtype.UUID
	Name          string
	Position      int32
}

type CompetitionFlightCategory struct {
	CompetitionID  pgtype.UUID
	FlightID       pgtype.UUID
	Gender         Gender
	WeightCategory string
}

type CompetitionMovement struct {
	ID            pgtype.UUID
	CompetitionID pgtype.UUID
	Movement      string
	Position      int32
}

type CompetitionParticipant struct {
	ID             pgtype.UUID
	CompetitionID  pgtype.UUID
	AthleteID      pgtype.UUID
	Name           string
	CompetesOn     pgtype.Date
	BodyweightKg   pgtype.Numeric
	Gender         *Gender
	WeightCategory *string
}

type CompetitionScore struct {
	ParticipantID pgtype.UUID
	CompetitionID pgtype.UUID
	Score         interface{}
	AthleteID     pgtype.UUID
	TotalBaremeKg int32
	BodyweightKg  pgtype.Numeric
	Gender        *Gender
}

type DailyLog struct {
	AthleteID   pgtype.UUID
	LogDate     pgtype.Date
	WeightKg    pgtype.Numeric
	SleepHours  pgtype.Numeric
	WaterLiters pgtype.Numeric
	Calories    pgtype.Numeric
	CyclePhase  *CyclePhase
}

type Douleur struct {
	ID        pgtype.UUID
	AthleteID pgtype.UUID
	Nom       string
	Zone      string
	Debut     pgtype.Date
	Fin       pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type DouleurLog struct {
	ID           pgtype.UUID
	DouleurID    pgtype.UUID
	LogDate      pgtype.Date
	Intensite    int16
	Commentaire  *string
	Entrainement *bool
	CreatedAt    pgtype.Timestamptz
	ModifieLe    pgtype.Timestamptz
}

type Kine struct {
	Uid       string
	CreatedAt pgtype.Timestamptz
	Structure string
}

type KineNote struct {
	ID        pgtype.UUID
	AthleteID pgtype.UUID
	KineUid   string
	Contenu   string
	CreeLe    pgtype.Timestamptz
	ModifieLe pgtype.Timestamptz
}

type LibraryEntry struct {
	ID          pgtype.UUID
	Category    LibraryCategory
	Name        string
	Competition bool
	Supports    []string
	CreatedBy   *string
	CreatedAt   pgtype.Timestamptz
	Structure   string
}

type NorepReason struct {
	ID     string
	Label  string
	IsAuto bool
}

type ObjectifsTechnique struct {
	ID        pgtype.UUID
	AthleteID pgtype.UUID
	Categorie LibraryCategory
	Mouvement string
	Structure string
	Texte     string
	CreePar   string
	CreeLe    pgtype.Timestamptz
	ClosLe    pgtype.Timestamptz
}

type Program struct {
	ID        string
	Name      *string
	CoachUid  string
	AthleteID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type PushSubscription struct {
	Endpoint  string
	Uid       string
	P256dh    string
	Auth      string
	CreatedAt pgtype.Timestamptz
}

type SchemaMigration struct {
	Fichier    string
	AppliqueLe pgtype.Timestamptz
}

type SignalementVu struct {
	AthleteID pgtype.UUID
	LogDate   pgtype.Date
	Uid       string
	VuLe      pgtype.Timestamptz
}

type Structure struct {
	Slug string
	Nom  string
}

type TrainingBaseAccessory struct {
	ID            pgtype.UUID
	BlockID       pgtype.UUID
	Position      int32
	Day           string
	Name          *string
	Variant       []string
	Kind          *string
	Format        *string
	ClusterMode   *string
	ClusterRest   *string
	Tempo         *string
	Sets          *string
	Reps          *string
	RepsUnit      *string
	Weight        *string
	WeightLocked  bool
	Assistance    *string
	AimedRpe      *string
	Rest          *string
	CoachNote     *string
	Increment     *string
	IncrementUnit *string
	GroupID       *string
	GroupKind     *string
	Unbroken      bool
	Categorie     LibraryCategory
	Structure     string
}

type TrainingBasePrinciple struct {
	ID            pgtype.UUID
	BlockID       pgtype.UUID
	Position      int32
	Name          *string
	Variant       []string
	Tier          int32
	Kind          *string
	Format        *string
	ClusterMode   *string
	ClusterRest   *string
	Tempo         *string
	Sets          *string
	Reps          *string
	RepsUnit      *string
	Weight        *string
	WeightLocked  bool
	Assistance    *string
	AimedRpe      *string
	Rest          *string
	CoachNote     *string
	Increment     *string
	IncrementUnit *string
	Categorie     LibraryCategory
	Structure     string
}

type TrainingBlock struct {
	ID                 pgtype.UUID
	SourceUpdatedAt    pgtype.Timestamptz
	MacroID            pgtype.UUID
	LegacyID           string
	Number             int32
	Name               *string
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	DaySplit           []byte
	SelectedPrincipals []string
	Granularity        []byte
	S1StartDate        pgtype.Date
	S1EndDate          pgtype.Date
}

type TrainingExercise struct {
	ID              pgtype.UUID
	SessionID       pgtype.UUID
	Position        int32
	Kind            *string
	Name            *string
	Variant         []string
	Tier            *int32
	Format          *string
	ClusterMode     *string
	ClusterRest     *string
	Tempo           *string
	Sets            *string
	Reps            *string
	RepsUnit        *string
	Weight          *string
	WeightLocked    bool
	Assistance      *string
	AimedRpe        *string
	Rest            *string
	RepsDone        *string
	WeightDone      *string
	RestActual      *string
	FeltRpe         *string
	FeltRpeBySet    []string
	RepsDoneBySet   []string
	WeightDoneBySet []string
	ToursRealises   *int32
	AthleteFeedback *string
	CoachNote       *string
	Link            *string
	GroupID         *string
	GroupKind       *string
	Unbroken        bool
	Increment       *string
	IncrementUnit   *string
	Categorie       LibraryCategory
	Structure       string
}

type TrainingMacro struct {
	ID                pgtype.UUID
	ProgramID         string
	LegacyID          string
	Number            int32
	Name              *string
	TrainingFrequency *int32
	CoachNotes        *string
	SourceUpdatedAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type TrainingSession struct {
	ID           pgtype.UUID
	WeekID       pgtype.UUID
	LegacyID     string
	Position     int32
	Name         string
	SessionDate  pgtype.Date
	FormOfTheDay *int32
	RelueLe      pgtype.Timestamptz
	ReluePar     *string
	ModifieeLe   pgtype.Timestamptz
	ModifieePar  *string
}

type TrainingSet struct {
	ID              int64
	AthleteID       string
	ProgramID       string
	MacroNumber     *int32
	BlockNumber     *int32
	WeekNumber      *int32
	SessionIndex    int32
	SessionName     *string
	SessionDate     pgtype.Date
	DateExact       bool
	ExerciseIndex   int32
	Exercise        string
	ExerciseID      pgtype.UUID
	Variant         []string
	Assistance      *string
	Tempo           *string
	Format          *string
	Tier            *int32
	SupersetGroup   *string
	Kind            *string
	Sets            *int32
	Reps            pgtype.Numeric
	RepsHigh        pgtype.Numeric
	RepsDone        pgtype.Numeric
	RepsUnit        *string
	Bodyweight      bool
	WeightKg        pgtype.Numeric
	WeightDoneKg    pgtype.Numeric
	AimedRpe        pgtype.Numeric
	FeltRpe         pgtype.Numeric
	FeltRpeRaw      *string
	RpeBySet        []pgtype.Numeric
	RepsBySet       []pgtype.Numeric
	WeightBySet     []pgtype.Numeric
	RestS           pgtype.Numeric
	TonnageKg       pgtype.Numeric
	TonnagePrevuKg  pgtype.Numeric
	SetsPrevus      *int32
	Mechano         pgtype.Numeric
	AthleteFeedback *string
	CoachNote       *string
	Categorie       LibraryCategory
	Structure       string
}

type TrainingWeek struct {
	ID              pgtype.UUID
	SourceUpdatedAt pgtype.Timestamptz
	BlockID         pgtype.UUID
	LegacyID        string
	Number          int32
	Name            *string
	Hidden          bool
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	AthleteWeightKg pgtype.Numeric
	AthleteHeightCm pgtype.Numeric
}

type User struct {
	Uid         string
	Email       string
	DisplayName string
	IsAdmin     bool
	CreatedAt   pgtype.Timestamptz
	Preferences []byte
}

type WeightCategory struct {
	Gender   Gender
	Code     string
	MaxKg    pgtype.Numeric
	Position int32
}
