// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: socle.sql

package db

import (
	"context"
)

const estAdmin = `-- name: EstAdmin :one
SELECT COALESCE((SELECT u.is_admin FROM users u WHERE u.uid = $1), false)::boolean AS admin
`

func (q *Queries) EstAdmin(ctx context.Context, compte string) (bool, error) {
	row := q.db.QueryRow(ctx, estAdmin, compte)
	var admin bool
	err := row.Scan(&admin)
	return admin, err
}

const estCoach = `-- name: EstCoach :one
SELECT EXISTS(SELECT 1 FROM coaches c WHERE c.uid = $1)::boolean AS coach
`

func (q *Queries) EstCoach(ctx context.Context, compte string) (bool, error) {
	row := q.db.QueryRow(ctx, estCoach, compte)
	var coach bool
	err := row.Scan(&coach)
	return coach, err
}

const estMembre = `-- name: EstMembre :one

SELECT (EXISTS(SELECT 1 FROM coaches  c WHERE c.uid = $1)
     OR EXISTS(SELECT 1 FROM kines    k WHERE k.uid = $1)
     OR EXISTS(SELECT 1 FROM athletes a WHERE a.user_uid = $1)
     OR EXISTS(SELECT 1 FROM users    u WHERE u.uid = $1 AND u.is_admin))::boolean AS membre
`

// Qui est quoi : la résolution uid → rôles, et nulle part ailleurs.
// (Colonnes qualifiées partout : sans alias, sqlc croit `uid` ambigu entre
// les sous-requêtes d'un SELECT sans FROM.)
// Un lien RÉEL avec l'application : un rôle, ou une fiche athlète. Être
// authentifié n'est pas être membre — Firebase accepte tout compte Google.
func (q *Queries) EstMembre(ctx context.Context, compte string) (bool, error) {
	row := q.db.QueryRow(ctx, estMembre, compte)
	var membre bool
	err := row.Scan(&membre)
	return membre, err
}

const structureDuCoach = `-- name: StructureDuCoach :one
SELECT c.structure FROM coaches c WHERE c.uid = $1
`

func (q *Queries) StructureDuCoach(ctx context.Context, compte string) (string, error) {
	row := q.db.QueryRow(ctx, structureDuCoach, compte)
	var structure string
	err := row.Scan(&structure)
	return structure, err
}

const structuresDe = `-- name: StructuresDe :many
SELECT s.slug,
       EXISTS(SELECT 1 FROM coaches c WHERE c.uid = $1 AND c.structure = s.slug)::boolean AS est_coach,
       (EXISTS(SELECT 1 FROM kines k WHERE k.uid = $1 AND k.structure = s.slug)
        OR EXISTS(SELECT 1 FROM athletes a WHERE a.kine_uid = $1 AND a.structure = s.slug))::boolean AS est_kine,
       EXISTS(SELECT 1 FROM athletes a WHERE a.user_uid = $1 AND a.structure = s.slug)::boolean AS est_athlete,
       EXISTS(SELECT 1 FROM users u WHERE u.uid = $1 AND u.is_admin)::boolean AS est_admin
FROM structures s
ORDER BY s.slug <> $2::text, s.nom
`

type StructuresDeParams struct {
	Compte   string
	Premiere string
}

type StructuresDeRow struct {
	Slug       string
	EstCoach   bool
	EstKine    bool
	EstAthlete bool
	EstAdmin   bool
}

// Les structures de ce compte, chacune avec ce qu'il y EST. « Kiné » vaut
// aussi pour qui y SUIT un athlète sans y exercer. L'admin les voit toutes.
func (q *Queries) StructuresDe(ctx context.Context, arg StructuresDeParams) ([]StructuresDeRow, error) {
	rows, err := q.db.Query(ctx, structuresDe, arg.Compte, arg.Premiere)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructuresDeRow
	for rows.Next() {
		var i StructuresDeRow
		if err := rows.Scan(
			&i.Slug,
			&i.EstCoach,
			&i.EstKine,
			&i.EstAthlete,
			&i.EstAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
